#!/bin/bash

# Array of products with their categories
products=(
  # "Alpine Trekker Hiking Boots HIKING"
  # "Mountaineer's Hiking Backpack HIKING"
  # "Trek Support Hiking Poles HIKING"
  # "Outdoor Explorer's Camping Tent HIKING"
  # "Rugged Trail Hiking Socks HIKING"
  # "Hiker's Hydration Pack HIKING"
  # "PeakComfort Sleeping Bag HIKING"
  # "ProTrek Hiking Shorts HIKING"
  # "SunShield Hiker's Hat HIKING"
  # "TrailBlazer GPS Tracker HIKING"
  # "CourtMaster Basketball Shoes BASKETBALL"
  # "HoopShot Basketball BASKETBALL"
  # "SlamDunk Basketball Jersey BASKETBALL"
  # "BasketPro Ankle Support BASKETBALL"
  # "ScoreKing Basketball Shorts BASKETBALL"
  # "QuickDribble Basketball Gloves BASKETBALL"
  # "NetMaster Basketball Net BASKETBALL"
  # "JumpBoost Knee Pads BASKETBALL"
  # "SwishMaster Shooting Sleeves BASKETBALL"
  # "CourtVision Sports Glasses BASKETBALL"
  # "PunchKing Boxing Gloves BOXING"
  # "RingMaster Boxing Shoes BOXING"
  # "KnockOut Boxing Headgear BOXING"
  # "ChampGuard Mouthguard BOXING"
  # "StrikeForce Punching Bag BOXING"
  # "PowerPunch Boxing Pads BOXING"
  # "RingStar Boxing Shorts BOXING"
  # "FightFast Speed Bag BOXING"
  # "JabMaster Boxing Robe BOXING"
  # "GuardPro Boxing Hand Wraps BOXING"
  # "RunFast Pro Running Shoes RUNNING"
  # "Marathon Master Running Shorts RUNNING"
  # "TrackStar Running T-Shirt RUNNING"
  # "StridePro Running Socks RUNNING"
  # "HydraPack Running Water Bottle RUNNING"
  # "SpeedTrack Running Watch RUNNING"
  # "WindShield Running Jacket RUNNING"
  # "Energize Energy Gel Packs RUNNING"
  # "ComfortFit Running Headband RUNNING"
  # "NightVision Reflective Vest RUNNING"
  # "MatchPoint Pro Tennis Racket TENNIS"
  # "CourtMaster Tennis Shoes TENNIS"
  # "SwingPro Tennis Balls TENNIS"
  # "AceServe Tennis Shorts TENNIS"
  # "NetMaster Tennis Net TENNIS"
  # "TennisPro Elbow Brace TENNIS"
  # "GrandSlam Tennis Bag TENNIS"
  # "VolleyMaster Tennis Visor TENNIS"
  # "GripMax Racket Grips TENNIS"
  # "TennisPro Training Cones TENNIS"
  # "CampKing 2-Person Tent CAMPING"
  # "OutdoorChef Camping Stove CAMPING"
  # "StarGaze Sleeping Bag CAMPING"
  # "TravelLight Camping Backpack CAMPING"
  # "CampFire Portable Grill CAMPING"
  # "MountainSpring Camping Water Filter CAMPING"
  # "NightGuide Headlamp CAMPING"
  # "ComfyRest Camping Pillow CAMPING"
  # "OutdoorFirst Aid Kit CAMPING"
  # "NatureView Binoculars CAMPING"
  # "WaveRider Swimming Goggles SWIMMING"
  # "AquaSpeed Swim Cap SWIMMING"
  # "WaterPro Swim Fins SWIMMING"
  # "TideMaster Swimming Trunks SWIMMING"
  # "SplashFun Water Noodles SWIMMING"
  "SeaView Snorkel Set SWIMMING"
  "Guardian Life Vest SWIMMING"
  "SplashFun Water Noodles SWIMMING"
  "SeaView Snorkel Set SWIMMING"
  "Guardian Life Vest SWIMMING"
  "DiveMaster Diving Mask SWIMMING"
  "FlipTurn Swim Paddles SWIMMING"
  "BeachBuddy Beach Umbrella BEACH"
  "SunSeeker Beach Chair BEACH"
  "SandCastle Building Kit BEACH"
  "WaveRider Bodyboard BEACH"
  "ShoreLine Beach Bag BEACH"
  "BeachComber Sun Hat BEACH"
  "CoastGuard Beach Towel BEACH"
  "ShellSeeker Seashell Collection BEACH"
  "SunGuard Beach Tent BEACH"
  "Fisherman's Fishing Rod FISHING"
  "ReelMaster Fishing Reel FISHING"
  "BaitMate Fishing Lures FISHING"
  "Fisherman's Tackle Box FISHING"
  "Angler's Fishing Hat FISHING"
  "HookLine Fishing Line FISHING"
  "CatchPro Fishing Net FISHING"
  "FloatMaster Fishing Floats FISHING"
  "FishFinder Portable Fish Finder FISHING"
  "CastAway Fishing Rod Case FISHING"
)

# Loop through the products and fetch the corresponding image
for product in "${products[@]}"; do
  # Split the product string into name and category
  product_name="${product% *}"
  category="${product##* }"

  # Convert product name to lowercase and replace spaces with dashes
  product_slug=$(echo "$product_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

  # Fetch the image using wget and save with the product name
  wget -O "$product_name.jpg" "https://image.pollinations.ai/prompt/$product_slug,$category,%20hyper-realistic,%20realistic,%20ecommerce,%20presentation,%20object"
done
